name: homes
description: A sample Flutter project for adding home screen widgets.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  home_widget: ^0.3.0-alpha.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Chewy
      fonts:
        - asset: fonts/Chewy-Regular.ttf
